### ISSUE TITLE
可以支持 https 和 wss 吗？

### ISSUE THREAD

**Issue by NanoRocky** [hyperzlib/DG-Lab-Coyote-Game-Hub#4]
我自己修改了代码启用 https ，配置了ssl。但没能看懂 wss 逻辑，不会（）二维码目前还是 ws ，转了一会儿就无法连接。大佬可以适配一下嘛，谢谢！

**Comment by hyperzlib** [comment]
编写的时候是按照Nginx反向代理SSL设计的，具体看config.example-server.yaml

**Comment by hyperzlib** [comment]
不过目前还不确定DG-Lab的App是不是支持SSL，毕竟DG-Lab技术力在那里摆着……

**Comment by hyperzlib** [comment]
具体来说是

```mermaid
flowchart LR
A[浏览器] -->|HTTPS| B[Nginx]
B -->|HTTP| C[Coyote Game Hub]
```

这样的一个逻辑，本体不会做SSL支持，因为本地部署不需要，服务器部署基本上都要反向代理。然后config里有个```proxySSLEnable```配置项，可以把输出的所有URL（包括ws）转换成带SSL的URL。

**Comment by NanoRocky** [comment]
emmm...一顿胡乱操作，现在扫码能提示连接成功，服务器上也有连接日志，但网页没有反应且DG-LAB在10秒左右后自动断开连接并提示连接失败。不会整了....
关掉 https 关闭端口转发 扫码就会转5秒直接提示连接失败，也就是什么都不配置只放个域名。
我无法使用纯IP模式排除问题，因为腾讯云的网卡接口IP不等于直接的公网IP，用0.0.0.0则在选择页没IP可选，直接把IP填上去程序就会闪退。
至于支不支持，至少官方的文档示例里是用的wss，不清楚...
[调试](https://dg.nanorocky.top)

**Comment by hyperzlib** [comment]
你有没有看那个服务器部署版的config，我记得在服务器模式，选择框不会出现ip，会是域名

**Comment by hyperzlib** [comment]
我改了一下配置项，你现在再看看呢？之前会强制把当前端口加上去，反向代理后的端口其实要另外配置。

**Comment by NanoRocky** [comment]
> coyote-game-hub@1.0.0 start
> node server/index.js

MainConfig validation failed.
[
  {
    instancePath: '',
    schemaPath: '#/definitions/MainConfigType/required',
    keyword: 'required',
    params: { missingProperty: 'reverseProxy' },
    message: "must have required property 'reverseProxy'"
  }
]
Error: MainConfig validation failed.
    at MainConfig.initialize (\server\config.js:73:19)
    at async main (\server\index.js:24:5)

**Comment by NanoRocky** [comment]
噢，我并没有get仓库，直接下的Release，就没去看“config.example-server.yaml”..（）
现在的情况是..能连接了，网页端也能提示连接成功并能够成功下发指令了。但客户端还是在10秒后自动断开并提示连接失败，emm？

**Comment by NanoRocky** [comment]
我大概知道为什么了，腾讯的 CDN 策略，WebSocket 超时时间为10秒（）
关了cdn就好了
