### ISSUE TITLE
请求错误时不要返回 http status = 200

### ISSUE THREAD

**Issue by eigeen** [hyperzlib/DG-Lab-Coyote-Game-Hub#5]
如题，以便于在解析返回体结构前判断是否错误。

静态语言中，解析未知的json结构较为麻烦，需要先解析为动态结构判断字段，然后再映射到固定结构上。如果能提前通过http code获取是否为错误的信息会更好。

**Comment by hyperzlib** [comment]
关于这个，可以考虑加一个单独的http header。因为在某些非标准的编程语言中，http code不为200可能会出现无法解析响应的问题。

**Comment by eigeen** [comment]
已于 https://github.com/hyperzlib/DG-Lab-Coyote-Game-Hub/pull/6 中计划或实现。issue关闭。
